### ISSUE TITLE
Is there a way to customize my preferences?

### ISSUE THREAD

**Issue by Lil900** [Anupya/JapaneseTab#2]
I want to replace hiragana with kanji because kanji became small and I wish it could be bigger to notice the details

**Comment by Anupya** [comment]
Oh! I switched the kanji and hiragana last Friday because I was informed by another user that most Japanese teachers prefer you learn hiragana first. 
You are free to look at the code and submit a pull request in the meantime if you'd like!
(tldr; I am on co-op and only have so much time but I will do it if more people ask me =D )

**Comment by azz** [comment]
Came to ask the same thing - Kanji should be larger as it is how you will actually see it written in Japanese.

**Comment by clausagerskov** [comment]
so this will not be fixed?

**Comment by clausagerskov** [comment]
fixed it myself, submitted a pull request

**Comment by Anupya** [comment]
Hello! You can now customize whether you want kanji/hiragana in focus and toggle romaji on/off. Please click on the Menu button on the top left. My implementation is different than Claus' because I am not a fan of using the Options page.
